/* automatically generated by rust-bindgen 0.72.1 */

pub type RimeSessionId = usize;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_traits_t {
    pub data_size: ::std::os::raw::c_int,
    pub shared_data_dir: *const ::std::os::raw::c_char,
    pub user_data_dir: *const ::std::os::raw::c_char,
    pub distribution_name: *const ::std::os::raw::c_char,
    pub distribution_code_name: *const ::std::os::raw::c_char,
    pub distribution_version: *const ::std::os::raw::c_char,
    pub app_name: *const ::std::os::raw::c_char,
    pub modules: *mut *const ::std::os::raw::c_char,
    pub min_log_level: ::std::os::raw::c_int,
    pub log_dir: *const ::std::os::raw::c_char,
    pub prebuilt_data_dir: *const ::std::os::raw::c_char,
    pub staging_dir: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_traits_t"][::std::mem::size_of::<rime_traits_t>() - 96usize];
    ["Alignment of rime_traits_t"][::std::mem::align_of::<rime_traits_t>() - 8usize];
    ["Offset of field: rime_traits_t::data_size"]
        [::std::mem::offset_of!(rime_traits_t, data_size) - 0usize];
    ["Offset of field: rime_traits_t::shared_data_dir"]
        [::std::mem::offset_of!(rime_traits_t, shared_data_dir) - 8usize];
    ["Offset of field: rime_traits_t::user_data_dir"]
        [::std::mem::offset_of!(rime_traits_t, user_data_dir) - 16usize];
    ["Offset of field: rime_traits_t::distribution_name"]
        [::std::mem::offset_of!(rime_traits_t, distribution_name) - 24usize];
    ["Offset of field: rime_traits_t::distribution_code_name"]
        [::std::mem::offset_of!(rime_traits_t, distribution_code_name) - 32usize];
    ["Offset of field: rime_traits_t::distribution_version"]
        [::std::mem::offset_of!(rime_traits_t, distribution_version) - 40usize];
    ["Offset of field: rime_traits_t::app_name"]
        [::std::mem::offset_of!(rime_traits_t, app_name) - 48usize];
    ["Offset of field: rime_traits_t::modules"]
        [::std::mem::offset_of!(rime_traits_t, modules) - 56usize];
    ["Offset of field: rime_traits_t::min_log_level"]
        [::std::mem::offset_of!(rime_traits_t, min_log_level) - 64usize];
    ["Offset of field: rime_traits_t::log_dir"]
        [::std::mem::offset_of!(rime_traits_t, log_dir) - 72usize];
    ["Offset of field: rime_traits_t::prebuilt_data_dir"]
        [::std::mem::offset_of!(rime_traits_t, prebuilt_data_dir) - 80usize];
    ["Offset of field: rime_traits_t::staging_dir"]
        [::std::mem::offset_of!(rime_traits_t, staging_dir) - 88usize];
};
impl Default for rime_traits_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeTraits = rime_traits_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RimeComposition {
    pub length: ::std::os::raw::c_int,
    pub cursor_pos: ::std::os::raw::c_int,
    pub sel_start: ::std::os::raw::c_int,
    pub sel_end: ::std::os::raw::c_int,
    pub preedit: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RimeComposition"][::std::mem::size_of::<RimeComposition>() - 24usize];
    ["Alignment of RimeComposition"][::std::mem::align_of::<RimeComposition>() - 8usize];
    ["Offset of field: RimeComposition::length"]
        [::std::mem::offset_of!(RimeComposition, length) - 0usize];
    ["Offset of field: RimeComposition::cursor_pos"]
        [::std::mem::offset_of!(RimeComposition, cursor_pos) - 4usize];
    ["Offset of field: RimeComposition::sel_start"]
        [::std::mem::offset_of!(RimeComposition, sel_start) - 8usize];
    ["Offset of field: RimeComposition::sel_end"]
        [::std::mem::offset_of!(RimeComposition, sel_end) - 12usize];
    ["Offset of field: RimeComposition::preedit"]
        [::std::mem::offset_of!(RimeComposition, preedit) - 16usize];
};
impl Default for RimeComposition {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_candidate_t {
    pub text: *mut ::std::os::raw::c_char,
    pub comment: *mut ::std::os::raw::c_char,
    pub reserved: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_candidate_t"][::std::mem::size_of::<rime_candidate_t>() - 24usize];
    ["Alignment of rime_candidate_t"][::std::mem::align_of::<rime_candidate_t>() - 8usize];
    ["Offset of field: rime_candidate_t::text"]
        [::std::mem::offset_of!(rime_candidate_t, text) - 0usize];
    ["Offset of field: rime_candidate_t::comment"]
        [::std::mem::offset_of!(rime_candidate_t, comment) - 8usize];
    ["Offset of field: rime_candidate_t::reserved"]
        [::std::mem::offset_of!(rime_candidate_t, reserved) - 16usize];
};
impl Default for rime_candidate_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeCandidate = rime_candidate_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct RimeMenu {
    pub page_size: ::std::os::raw::c_int,
    pub page_no: ::std::os::raw::c_int,
    pub is_last_page: ::std::os::raw::c_int,
    pub highlighted_candidate_index: ::std::os::raw::c_int,
    pub num_candidates: ::std::os::raw::c_int,
    pub candidates: *mut RimeCandidate,
    pub select_keys: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of RimeMenu"][::std::mem::size_of::<RimeMenu>() - 40usize];
    ["Alignment of RimeMenu"][::std::mem::align_of::<RimeMenu>() - 8usize];
    ["Offset of field: RimeMenu::page_size"][::std::mem::offset_of!(RimeMenu, page_size) - 0usize];
    ["Offset of field: RimeMenu::page_no"][::std::mem::offset_of!(RimeMenu, page_no) - 4usize];
    ["Offset of field: RimeMenu::is_last_page"]
        [::std::mem::offset_of!(RimeMenu, is_last_page) - 8usize];
    ["Offset of field: RimeMenu::highlighted_candidate_index"]
        [::std::mem::offset_of!(RimeMenu, highlighted_candidate_index) - 12usize];
    ["Offset of field: RimeMenu::num_candidates"]
        [::std::mem::offset_of!(RimeMenu, num_candidates) - 16usize];
    ["Offset of field: RimeMenu::candidates"]
        [::std::mem::offset_of!(RimeMenu, candidates) - 24usize];
    ["Offset of field: RimeMenu::select_keys"]
        [::std::mem::offset_of!(RimeMenu, select_keys) - 32usize];
};
impl Default for RimeMenu {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_commit_t {
    pub data_size: ::std::os::raw::c_int,
    pub text: *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_commit_t"][::std::mem::size_of::<rime_commit_t>() - 16usize];
    ["Alignment of rime_commit_t"][::std::mem::align_of::<rime_commit_t>() - 8usize];
    ["Offset of field: rime_commit_t::data_size"]
        [::std::mem::offset_of!(rime_commit_t, data_size) - 0usize];
    ["Offset of field: rime_commit_t::text"][::std::mem::offset_of!(rime_commit_t, text) - 8usize];
};
impl Default for rime_commit_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeCommit = rime_commit_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_context_t {
    pub data_size: ::std::os::raw::c_int,
    pub composition: RimeComposition,
    pub menu: RimeMenu,
    pub commit_text_preview: *mut ::std::os::raw::c_char,
    pub select_labels: *mut *mut ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_context_t"][::std::mem::size_of::<rime_context_t>() - 88usize];
    ["Alignment of rime_context_t"][::std::mem::align_of::<rime_context_t>() - 8usize];
    ["Offset of field: rime_context_t::data_size"]
        [::std::mem::offset_of!(rime_context_t, data_size) - 0usize];
    ["Offset of field: rime_context_t::composition"]
        [::std::mem::offset_of!(rime_context_t, composition) - 8usize];
    ["Offset of field: rime_context_t::menu"]
        [::std::mem::offset_of!(rime_context_t, menu) - 32usize];
    ["Offset of field: rime_context_t::commit_text_preview"]
        [::std::mem::offset_of!(rime_context_t, commit_text_preview) - 72usize];
    ["Offset of field: rime_context_t::select_labels"]
        [::std::mem::offset_of!(rime_context_t, select_labels) - 80usize];
};
impl Default for rime_context_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeContext = rime_context_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_status_t {
    pub data_size: ::std::os::raw::c_int,
    pub schema_id: *mut ::std::os::raw::c_char,
    pub schema_name: *mut ::std::os::raw::c_char,
    pub is_disabled: ::std::os::raw::c_int,
    pub is_composing: ::std::os::raw::c_int,
    pub is_ascii_mode: ::std::os::raw::c_int,
    pub is_full_shape: ::std::os::raw::c_int,
    pub is_simplified: ::std::os::raw::c_int,
    pub is_traditional: ::std::os::raw::c_int,
    pub is_ascii_punct: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_status_t"][::std::mem::size_of::<rime_status_t>() - 56usize];
    ["Alignment of rime_status_t"][::std::mem::align_of::<rime_status_t>() - 8usize];
    ["Offset of field: rime_status_t::data_size"]
        [::std::mem::offset_of!(rime_status_t, data_size) - 0usize];
    ["Offset of field: rime_status_t::schema_id"]
        [::std::mem::offset_of!(rime_status_t, schema_id) - 8usize];
    ["Offset of field: rime_status_t::schema_name"]
        [::std::mem::offset_of!(rime_status_t, schema_name) - 16usize];
    ["Offset of field: rime_status_t::is_disabled"]
        [::std::mem::offset_of!(rime_status_t, is_disabled) - 24usize];
    ["Offset of field: rime_status_t::is_composing"]
        [::std::mem::offset_of!(rime_status_t, is_composing) - 28usize];
    ["Offset of field: rime_status_t::is_ascii_mode"]
        [::std::mem::offset_of!(rime_status_t, is_ascii_mode) - 32usize];
    ["Offset of field: rime_status_t::is_full_shape"]
        [::std::mem::offset_of!(rime_status_t, is_full_shape) - 36usize];
    ["Offset of field: rime_status_t::is_simplified"]
        [::std::mem::offset_of!(rime_status_t, is_simplified) - 40usize];
    ["Offset of field: rime_status_t::is_traditional"]
        [::std::mem::offset_of!(rime_status_t, is_traditional) - 44usize];
    ["Offset of field: rime_status_t::is_ascii_punct"]
        [::std::mem::offset_of!(rime_status_t, is_ascii_punct) - 48usize];
};
impl Default for rime_status_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeStatus = rime_status_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_candidate_list_iterator_t {
    pub ptr: *mut ::std::os::raw::c_void,
    pub index: ::std::os::raw::c_int,
    pub candidate: RimeCandidate,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_candidate_list_iterator_t"]
        [::std::mem::size_of::<rime_candidate_list_iterator_t>() - 40usize];
    ["Alignment of rime_candidate_list_iterator_t"]
        [::std::mem::align_of::<rime_candidate_list_iterator_t>() - 8usize];
    ["Offset of field: rime_candidate_list_iterator_t::ptr"]
        [::std::mem::offset_of!(rime_candidate_list_iterator_t, ptr) - 0usize];
    ["Offset of field: rime_candidate_list_iterator_t::index"]
        [::std::mem::offset_of!(rime_candidate_list_iterator_t, index) - 8usize];
    ["Offset of field: rime_candidate_list_iterator_t::candidate"]
        [::std::mem::offset_of!(rime_candidate_list_iterator_t, candidate) - 16usize];
};
impl Default for rime_candidate_list_iterator_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeCandidateListIterator = rime_candidate_list_iterator_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_config_t {
    pub ptr: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_config_t"][::std::mem::size_of::<rime_config_t>() - 8usize];
    ["Alignment of rime_config_t"][::std::mem::align_of::<rime_config_t>() - 8usize];
    ["Offset of field: rime_config_t::ptr"][::std::mem::offset_of!(rime_config_t, ptr) - 0usize];
};
impl Default for rime_config_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeConfig = rime_config_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_config_iterator_t {
    pub list: *mut ::std::os::raw::c_void,
    pub map: *mut ::std::os::raw::c_void,
    pub index: ::std::os::raw::c_int,
    pub key: *const ::std::os::raw::c_char,
    pub path: *const ::std::os::raw::c_char,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_config_iterator_t"][::std::mem::size_of::<rime_config_iterator_t>() - 40usize];
    ["Alignment of rime_config_iterator_t"]
        [::std::mem::align_of::<rime_config_iterator_t>() - 8usize];
    ["Offset of field: rime_config_iterator_t::list"]
        [::std::mem::offset_of!(rime_config_iterator_t, list) - 0usize];
    ["Offset of field: rime_config_iterator_t::map"]
        [::std::mem::offset_of!(rime_config_iterator_t, map) - 8usize];
    ["Offset of field: rime_config_iterator_t::index"]
        [::std::mem::offset_of!(rime_config_iterator_t, index) - 16usize];
    ["Offset of field: rime_config_iterator_t::key"]
        [::std::mem::offset_of!(rime_config_iterator_t, key) - 24usize];
    ["Offset of field: rime_config_iterator_t::path"]
        [::std::mem::offset_of!(rime_config_iterator_t, path) - 32usize];
};
impl Default for rime_config_iterator_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeConfigIterator = rime_config_iterator_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_schema_list_item_t {
    pub schema_id: *mut ::std::os::raw::c_char,
    pub name: *mut ::std::os::raw::c_char,
    pub reserved: *mut ::std::os::raw::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_schema_list_item_t"][::std::mem::size_of::<rime_schema_list_item_t>() - 24usize];
    ["Alignment of rime_schema_list_item_t"]
        [::std::mem::align_of::<rime_schema_list_item_t>() - 8usize];
    ["Offset of field: rime_schema_list_item_t::schema_id"]
        [::std::mem::offset_of!(rime_schema_list_item_t, schema_id) - 0usize];
    ["Offset of field: rime_schema_list_item_t::name"]
        [::std::mem::offset_of!(rime_schema_list_item_t, name) - 8usize];
    ["Offset of field: rime_schema_list_item_t::reserved"]
        [::std::mem::offset_of!(rime_schema_list_item_t, reserved) - 16usize];
};
impl Default for rime_schema_list_item_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeSchemaListItem = rime_schema_list_item_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_schema_list_t {
    pub size: usize,
    pub list: *mut RimeSchemaListItem,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_schema_list_t"][::std::mem::size_of::<rime_schema_list_t>() - 16usize];
    ["Alignment of rime_schema_list_t"][::std::mem::align_of::<rime_schema_list_t>() - 8usize];
    ["Offset of field: rime_schema_list_t::size"]
        [::std::mem::offset_of!(rime_schema_list_t, size) - 0usize];
    ["Offset of field: rime_schema_list_t::list"]
        [::std::mem::offset_of!(rime_schema_list_t, list) - 8usize];
};
impl Default for rime_schema_list_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeSchemaList = rime_schema_list_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_string_slice_t {
    pub str_: *const ::std::os::raw::c_char,
    pub length: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_string_slice_t"][::std::mem::size_of::<rime_string_slice_t>() - 16usize];
    ["Alignment of rime_string_slice_t"][::std::mem::align_of::<rime_string_slice_t>() - 8usize];
    ["Offset of field: rime_string_slice_t::str_"]
        [::std::mem::offset_of!(rime_string_slice_t, str_) - 0usize];
    ["Offset of field: rime_string_slice_t::length"]
        [::std::mem::offset_of!(rime_string_slice_t, length) - 8usize];
};
impl Default for rime_string_slice_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeStringSlice = rime_string_slice_t;
pub type RimeNotificationHandler = ::std::option::Option<
    unsafe extern "C" fn(
        context_object: *mut ::std::os::raw::c_void,
        session_id: RimeSessionId,
        message_type: *const ::std::os::raw::c_char,
        message_value: *const ::std::os::raw::c_char,
    ),
>;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct rime_custom_api_t {
    pub data_size: ::std::os::raw::c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_custom_api_t"][::std::mem::size_of::<rime_custom_api_t>() - 4usize];
    ["Alignment of rime_custom_api_t"][::std::mem::align_of::<rime_custom_api_t>() - 4usize];
    ["Offset of field: rime_custom_api_t::data_size"]
        [::std::mem::offset_of!(rime_custom_api_t, data_size) - 0usize];
};
pub type RimeCustomApi = rime_custom_api_t;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct rime_module_t {
    pub data_size: ::std::os::raw::c_int,
    pub module_name: *const ::std::os::raw::c_char,
    pub initialize: ::std::option::Option<unsafe extern "C" fn()>,
    pub finalize: ::std::option::Option<unsafe extern "C" fn()>,
    pub get_api: ::std::option::Option<unsafe extern "C" fn() -> *mut RimeCustomApi>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_module_t"][::std::mem::size_of::<rime_module_t>() - 40usize];
    ["Alignment of rime_module_t"][::std::mem::align_of::<rime_module_t>() - 8usize];
    ["Offset of field: rime_module_t::data_size"]
        [::std::mem::offset_of!(rime_module_t, data_size) - 0usize];
    ["Offset of field: rime_module_t::module_name"]
        [::std::mem::offset_of!(rime_module_t, module_name) - 8usize];
    ["Offset of field: rime_module_t::initialize"]
        [::std::mem::offset_of!(rime_module_t, initialize) - 16usize];
    ["Offset of field: rime_module_t::finalize"]
        [::std::mem::offset_of!(rime_module_t, finalize) - 24usize];
    ["Offset of field: rime_module_t::get_api"]
        [::std::mem::offset_of!(rime_module_t, get_api) - 32usize];
};
impl Default for rime_module_t {
    fn default() -> Self {
        let mut s = ::std::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::std::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
pub type RimeModule = rime_module_t;
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct rime_api_t {
    pub data_size: ::std::os::raw::c_int,
    pub setup: ::std::option::Option<unsafe extern "C" fn(traits: *mut RimeTraits)>,
    pub set_notification_handler: ::std::option::Option<
        unsafe extern "C" fn(
            handler: RimeNotificationHandler,
            context_object: *mut ::std::os::raw::c_void,
        ),
    >,
    pub initialize: ::std::option::Option<unsafe extern "C" fn(traits: *mut RimeTraits)>,
    pub finalize: ::std::option::Option<unsafe extern "C" fn()>,
    pub start_maintenance: ::std::option::Option<
        unsafe extern "C" fn(full_check: ::std::os::raw::c_int) -> ::std::os::raw::c_int,
    >,
    pub is_maintenance_mode: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub join_maintenance_thread: ::std::option::Option<unsafe extern "C" fn()>,
    pub deployer_initialize: ::std::option::Option<unsafe extern "C" fn(traits: *mut RimeTraits)>,
    pub prebuild: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub deploy: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub deploy_schema: ::std::option::Option<
        unsafe extern "C" fn(schema_file: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub deploy_config_file: ::std::option::Option<
        unsafe extern "C" fn(
            file_name: *const ::std::os::raw::c_char,
            version_key: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub sync_user_data: ::std::option::Option<unsafe extern "C" fn() -> ::std::os::raw::c_int>,
    pub create_session: ::std::option::Option<unsafe extern "C" fn() -> RimeSessionId>,
    pub find_session: ::std::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId) -> ::std::os::raw::c_int,
    >,
    pub destroy_session: ::std::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId) -> ::std::os::raw::c_int,
    >,
    pub cleanup_stale_sessions: ::std::option::Option<unsafe extern "C" fn()>,
    pub cleanup_all_sessions: ::std::option::Option<unsafe extern "C" fn()>,
    pub process_key: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            keycode: ::std::os::raw::c_int,
            mask: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub commit_composition: ::std::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId) -> ::std::os::raw::c_int,
    >,
    pub clear_composition: ::std::option::Option<unsafe extern "C" fn(session_id: RimeSessionId)>,
    pub get_commit: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            commit: *mut RimeCommit,
        ) -> ::std::os::raw::c_int,
    >,
    pub free_commit: ::std::option::Option<
        unsafe extern "C" fn(commit: *mut RimeCommit) -> ::std::os::raw::c_int,
    >,
    pub get_context: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            context: *mut RimeContext,
        ) -> ::std::os::raw::c_int,
    >,
    pub free_context:
        ::std::option::Option<unsafe extern "C" fn(ctx: *mut RimeContext) -> ::std::os::raw::c_int>,
    pub get_status: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            status: *mut RimeStatus,
        ) -> ::std::os::raw::c_int,
    >,
    pub free_status: ::std::option::Option<
        unsafe extern "C" fn(status: *mut RimeStatus) -> ::std::os::raw::c_int,
    >,
    pub set_option: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            option: *const ::std::os::raw::c_char,
            value: ::std::os::raw::c_int,
        ),
    >,
    pub get_option: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            option: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub set_property: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            prop: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        ),
    >,
    pub get_property: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            prop: *const ::std::os::raw::c_char,
            value: *mut ::std::os::raw::c_char,
            buffer_size: usize,
        ) -> ::std::os::raw::c_int,
    >,
    pub get_schema_list: ::std::option::Option<
        unsafe extern "C" fn(schema_list: *mut RimeSchemaList) -> ::std::os::raw::c_int,
    >,
    pub free_schema_list:
        ::std::option::Option<unsafe extern "C" fn(schema_list: *mut RimeSchemaList)>,
    pub get_current_schema: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            schema_id: *mut ::std::os::raw::c_char,
            buffer_size: usize,
        ) -> ::std::os::raw::c_int,
    >,
    pub select_schema: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            schema_id: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub schema_open: ::std::option::Option<
        unsafe extern "C" fn(
            schema_id: *const ::std::os::raw::c_char,
            config: *mut RimeConfig,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_open: ::std::option::Option<
        unsafe extern "C" fn(
            config_id: *const ::std::os::raw::c_char,
            config: *mut RimeConfig,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_close: ::std::option::Option<
        unsafe extern "C" fn(config: *mut RimeConfig) -> ::std::os::raw::c_int,
    >,
    pub config_get_bool: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
            value: *mut ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_get_int: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
            value: *mut ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_get_double: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
            value: *mut f64,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_get_string: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
            value: *mut ::std::os::raw::c_char,
            buffer_size: usize,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_get_cstring: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub config_update_signature: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            signer: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_begin_map: ::std::option::Option<
        unsafe extern "C" fn(
            iterator: *mut RimeConfigIterator,
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_next: ::std::option::Option<
        unsafe extern "C" fn(iterator: *mut RimeConfigIterator) -> ::std::os::raw::c_int,
    >,
    pub config_end: ::std::option::Option<unsafe extern "C" fn(iterator: *mut RimeConfigIterator)>,
    pub simulate_key_sequence: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            key_sequence: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub register_module: ::std::option::Option<
        unsafe extern "C" fn(module: *mut RimeModule) -> ::std::os::raw::c_int,
    >,
    pub find_module: ::std::option::Option<
        unsafe extern "C" fn(module_name: *const ::std::os::raw::c_char) -> *mut RimeModule,
    >,
    pub run_task: ::std::option::Option<
        unsafe extern "C" fn(task_name: *const ::std::os::raw::c_char) -> ::std::os::raw::c_int,
    >,
    pub get_shared_data_dir:
        ::std::option::Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char>,
    pub get_user_data_dir:
        ::std::option::Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char>,
    pub get_sync_dir:
        ::std::option::Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char>,
    pub get_user_id: ::std::option::Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char>,
    pub get_user_data_sync_dir: ::std::option::Option<
        unsafe extern "C" fn(dir: *mut ::std::os::raw::c_char, buffer_size: usize),
    >,
    pub config_init: ::std::option::Option<
        unsafe extern "C" fn(config: *mut RimeConfig) -> ::std::os::raw::c_int,
    >,
    pub config_load_string: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            yaml: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_set_bool: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
            value: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_set_int: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
            value: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_set_double: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
            value: f64,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_set_string: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
            value: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_get_item: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
            value: *mut RimeConfig,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_set_item: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
            value: *mut RimeConfig,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_clear: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_create_list: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_create_map: ::std::option::Option<
        unsafe extern "C" fn(
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub config_list_size: ::std::option::Option<
        unsafe extern "C" fn(config: *mut RimeConfig, key: *const ::std::os::raw::c_char) -> usize,
    >,
    pub config_begin_list: ::std::option::Option<
        unsafe extern "C" fn(
            iterator: *mut RimeConfigIterator,
            config: *mut RimeConfig,
            key: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub get_input: ::std::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId) -> *const ::std::os::raw::c_char,
    >,
    pub get_caret_pos:
        ::std::option::Option<unsafe extern "C" fn(session_id: RimeSessionId) -> usize>,
    pub select_candidate: ::std::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::std::os::raw::c_int,
    >,
    pub get_version: ::std::option::Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char>,
    pub set_caret_pos:
        ::std::option::Option<unsafe extern "C" fn(session_id: RimeSessionId, caret_pos: usize)>,
    pub select_candidate_on_current_page: ::std::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::std::os::raw::c_int,
    >,
    pub candidate_list_begin: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            iterator: *mut RimeCandidateListIterator,
        ) -> ::std::os::raw::c_int,
    >,
    pub candidate_list_next: ::std::option::Option<
        unsafe extern "C" fn(iterator: *mut RimeCandidateListIterator) -> ::std::os::raw::c_int,
    >,
    pub candidate_list_end:
        ::std::option::Option<unsafe extern "C" fn(iterator: *mut RimeCandidateListIterator)>,
    pub user_config_open: ::std::option::Option<
        unsafe extern "C" fn(
            config_id: *const ::std::os::raw::c_char,
            config: *mut RimeConfig,
        ) -> ::std::os::raw::c_int,
    >,
    pub candidate_list_from_index: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            iterator: *mut RimeCandidateListIterator,
            index: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
    pub get_prebuilt_data_dir:
        ::std::option::Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char>,
    pub get_staging_dir:
        ::std::option::Option<unsafe extern "C" fn() -> *const ::std::os::raw::c_char>,
    pub commit_proto: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            commit_builder: *mut ::std::os::raw::c_void,
        ),
    >,
    pub context_proto: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            context_builder: *mut ::std::os::raw::c_void,
        ),
    >,
    pub status_proto: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            status_builder: *mut ::std::os::raw::c_void,
        ),
    >,
    pub get_state_label: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            option_name: *const ::std::os::raw::c_char,
            state: ::std::os::raw::c_int,
        ) -> *const ::std::os::raw::c_char,
    >,
    pub delete_candidate: ::std::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::std::os::raw::c_int,
    >,
    pub delete_candidate_on_current_page: ::std::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::std::os::raw::c_int,
    >,
    pub get_state_label_abbreviated: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            option_name: *const ::std::os::raw::c_char,
            state: ::std::os::raw::c_int,
            abbreviated: ::std::os::raw::c_int,
        ) -> RimeStringSlice,
    >,
    pub set_input: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            input: *const ::std::os::raw::c_char,
        ) -> ::std::os::raw::c_int,
    >,
    pub get_shared_data_dir_s: ::std::option::Option<
        unsafe extern "C" fn(dir: *mut ::std::os::raw::c_char, buffer_size: usize),
    >,
    pub get_user_data_dir_s: ::std::option::Option<
        unsafe extern "C" fn(dir: *mut ::std::os::raw::c_char, buffer_size: usize),
    >,
    pub get_prebuilt_data_dir_s: ::std::option::Option<
        unsafe extern "C" fn(dir: *mut ::std::os::raw::c_char, buffer_size: usize),
    >,
    pub get_staging_dir_s: ::std::option::Option<
        unsafe extern "C" fn(dir: *mut ::std::os::raw::c_char, buffer_size: usize),
    >,
    pub get_sync_dir_s: ::std::option::Option<
        unsafe extern "C" fn(dir: *mut ::std::os::raw::c_char, buffer_size: usize),
    >,
    pub highlight_candidate: ::std::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::std::os::raw::c_int,
    >,
    pub highlight_candidate_on_current_page: ::std::option::Option<
        unsafe extern "C" fn(session_id: RimeSessionId, index: usize) -> ::std::os::raw::c_int,
    >,
    pub change_page: ::std::option::Option<
        unsafe extern "C" fn(
            session_id: RimeSessionId,
            backward: ::std::os::raw::c_int,
        ) -> ::std::os::raw::c_int,
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of rime_api_t"][::std::mem::size_of::<rime_api_t>() - 792usize];
    ["Alignment of rime_api_t"][::std::mem::align_of::<rime_api_t>() - 8usize];
    ["Offset of field: rime_api_t::data_size"]
        [::std::mem::offset_of!(rime_api_t, data_size) - 0usize];
    ["Offset of field: rime_api_t::setup"][::std::mem::offset_of!(rime_api_t, setup) - 8usize];
    ["Offset of field: rime_api_t::set_notification_handler"]
        [::std::mem::offset_of!(rime_api_t, set_notification_handler) - 16usize];
    ["Offset of field: rime_api_t::initialize"]
        [::std::mem::offset_of!(rime_api_t, initialize) - 24usize];
    ["Offset of field: rime_api_t::finalize"]
        [::std::mem::offset_of!(rime_api_t, finalize) - 32usize];
    ["Offset of field: rime_api_t::start_maintenance"]
        [::std::mem::offset_of!(rime_api_t, start_maintenance) - 40usize];
    ["Offset of field: rime_api_t::is_maintenance_mode"]
        [::std::mem::offset_of!(rime_api_t, is_maintenance_mode) - 48usize];
    ["Offset of field: rime_api_t::join_maintenance_thread"]
        [::std::mem::offset_of!(rime_api_t, join_maintenance_thread) - 56usize];
    ["Offset of field: rime_api_t::deployer_initialize"]
        [::std::mem::offset_of!(rime_api_t, deployer_initialize) - 64usize];
    ["Offset of field: rime_api_t::prebuild"]
        [::std::mem::offset_of!(rime_api_t, prebuild) - 72usize];
    ["Offset of field: rime_api_t::deploy"][::std::mem::offset_of!(rime_api_t, deploy) - 80usize];
    ["Offset of field: rime_api_t::deploy_schema"]
        [::std::mem::offset_of!(rime_api_t, deploy_schema) - 88usize];
    ["Offset of field: rime_api_t::deploy_config_file"]
        [::std::mem::offset_of!(rime_api_t, deploy_config_file) - 96usize];
    ["Offset of field: rime_api_t::sync_user_data"]
        [::std::mem::offset_of!(rime_api_t, sync_user_data) - 104usize];
    ["Offset of field: rime_api_t::create_session"]
        [::std::mem::offset_of!(rime_api_t, create_session) - 112usize];
    ["Offset of field: rime_api_t::find_session"]
        [::std::mem::offset_of!(rime_api_t, find_session) - 120usize];
    ["Offset of field: rime_api_t::destroy_session"]
        [::std::mem::offset_of!(rime_api_t, destroy_session) - 128usize];
    ["Offset of field: rime_api_t::cleanup_stale_sessions"]
        [::std::mem::offset_of!(rime_api_t, cleanup_stale_sessions) - 136usize];
    ["Offset of field: rime_api_t::cleanup_all_sessions"]
        [::std::mem::offset_of!(rime_api_t, cleanup_all_sessions) - 144usize];
    ["Offset of field: rime_api_t::process_key"]
        [::std::mem::offset_of!(rime_api_t, process_key) - 152usize];
    ["Offset of field: rime_api_t::commit_composition"]
        [::std::mem::offset_of!(rime_api_t, commit_composition) - 160usize];
    ["Offset of field: rime_api_t::clear_composition"]
        [::std::mem::offset_of!(rime_api_t, clear_composition) - 168usize];
    ["Offset of field: rime_api_t::get_commit"]
        [::std::mem::offset_of!(rime_api_t, get_commit) - 176usize];
    ["Offset of field: rime_api_t::free_commit"]
        [::std::mem::offset_of!(rime_api_t, free_commit) - 184usize];
    ["Offset of field: rime_api_t::get_context"]
        [::std::mem::offset_of!(rime_api_t, get_context) - 192usize];
    ["Offset of field: rime_api_t::free_context"]
        [::std::mem::offset_of!(rime_api_t, free_context) - 200usize];
    ["Offset of field: rime_api_t::get_status"]
        [::std::mem::offset_of!(rime_api_t, get_status) - 208usize];
    ["Offset of field: rime_api_t::free_status"]
        [::std::mem::offset_of!(rime_api_t, free_status) - 216usize];
    ["Offset of field: rime_api_t::set_option"]
        [::std::mem::offset_of!(rime_api_t, set_option) - 224usize];
    ["Offset of field: rime_api_t::get_option"]
        [::std::mem::offset_of!(rime_api_t, get_option) - 232usize];
    ["Offset of field: rime_api_t::set_property"]
        [::std::mem::offset_of!(rime_api_t, set_property) - 240usize];
    ["Offset of field: rime_api_t::get_property"]
        [::std::mem::offset_of!(rime_api_t, get_property) - 248usize];
    ["Offset of field: rime_api_t::get_schema_list"]
        [::std::mem::offset_of!(rime_api_t, get_schema_list) - 256usize];
    ["Offset of field: rime_api_t::free_schema_list"]
        [::std::mem::offset_of!(rime_api_t, free_schema_list) - 264usize];
    ["Offset of field: rime_api_t::get_current_schema"]
        [::std::mem::offset_of!(rime_api_t, get_current_schema) - 272usize];
    ["Offset of field: rime_api_t::select_schema"]
        [::std::mem::offset_of!(rime_api_t, select_schema) - 280usize];
    ["Offset of field: rime_api_t::schema_open"]
        [::std::mem::offset_of!(rime_api_t, schema_open) - 288usize];
    ["Offset of field: rime_api_t::config_open"]
        [::std::mem::offset_of!(rime_api_t, config_open) - 296usize];
    ["Offset of field: rime_api_t::config_close"]
        [::std::mem::offset_of!(rime_api_t, config_close) - 304usize];
    ["Offset of field: rime_api_t::config_get_bool"]
        [::std::mem::offset_of!(rime_api_t, config_get_bool) - 312usize];
    ["Offset of field: rime_api_t::config_get_int"]
        [::std::mem::offset_of!(rime_api_t, config_get_int) - 320usize];
    ["Offset of field: rime_api_t::config_get_double"]
        [::std::mem::offset_of!(rime_api_t, config_get_double) - 328usize];
    ["Offset of field: rime_api_t::config_get_string"]
        [::std::mem::offset_of!(rime_api_t, config_get_string) - 336usize];
    ["Offset of field: rime_api_t::config_get_cstring"]
        [::std::mem::offset_of!(rime_api_t, config_get_cstring) - 344usize];
    ["Offset of field: rime_api_t::config_update_signature"]
        [::std::mem::offset_of!(rime_api_t, config_update_signature) - 352usize];
    ["Offset of field: rime_api_t::config_begin_map"]
        [::std::mem::offset_of!(rime_api_t, config_begin_map) - 360usize];
    ["Offset of field: rime_api_t::config_next"]
        [::std::mem::offset_of!(rime_api_t, config_next) - 368usize];
    ["Offset of field: rime_api_t::config_end"]
        [::std::mem::offset_of!(rime_api_t, config_end) - 376usize];
    ["Offset of field: rime_api_t::simulate_key_sequence"]
        [::std::mem::offset_of!(rime_api_t, simulate_key_sequence) - 384usize];
    ["Offset of field: rime_api_t::register_module"]
        [::std::mem::offset_of!(rime_api_t, register_module) - 392usize];
    ["Offset of field: rime_api_t::find_module"]
        [::std::mem::offset_of!(rime_api_t, find_module) - 400usize];
    ["Offset of field: rime_api_t::run_task"]
        [::std::mem::offset_of!(rime_api_t, run_task) - 408usize];
    ["Offset of field: rime_api_t::get_shared_data_dir"]
        [::std::mem::offset_of!(rime_api_t, get_shared_data_dir) - 416usize];
    ["Offset of field: rime_api_t::get_user_data_dir"]
        [::std::mem::offset_of!(rime_api_t, get_user_data_dir) - 424usize];
    ["Offset of field: rime_api_t::get_sync_dir"]
        [::std::mem::offset_of!(rime_api_t, get_sync_dir) - 432usize];
    ["Offset of field: rime_api_t::get_user_id"]
        [::std::mem::offset_of!(rime_api_t, get_user_id) - 440usize];
    ["Offset of field: rime_api_t::get_user_data_sync_dir"]
        [::std::mem::offset_of!(rime_api_t, get_user_data_sync_dir) - 448usize];
    ["Offset of field: rime_api_t::config_init"]
        [::std::mem::offset_of!(rime_api_t, config_init) - 456usize];
    ["Offset of field: rime_api_t::config_load_string"]
        [::std::mem::offset_of!(rime_api_t, config_load_string) - 464usize];
    ["Offset of field: rime_api_t::config_set_bool"]
        [::std::mem::offset_of!(rime_api_t, config_set_bool) - 472usize];
    ["Offset of field: rime_api_t::config_set_int"]
        [::std::mem::offset_of!(rime_api_t, config_set_int) - 480usize];
    ["Offset of field: rime_api_t::config_set_double"]
        [::std::mem::offset_of!(rime_api_t, config_set_double) - 488usize];
    ["Offset of field: rime_api_t::config_set_string"]
        [::std::mem::offset_of!(rime_api_t, config_set_string) - 496usize];
    ["Offset of field: rime_api_t::config_get_item"]
        [::std::mem::offset_of!(rime_api_t, config_get_item) - 504usize];
    ["Offset of field: rime_api_t::config_set_item"]
        [::std::mem::offset_of!(rime_api_t, config_set_item) - 512usize];
    ["Offset of field: rime_api_t::config_clear"]
        [::std::mem::offset_of!(rime_api_t, config_clear) - 520usize];
    ["Offset of field: rime_api_t::config_create_list"]
        [::std::mem::offset_of!(rime_api_t, config_create_list) - 528usize];
    ["Offset of field: rime_api_t::config_create_map"]
        [::std::mem::offset_of!(rime_api_t, config_create_map) - 536usize];
    ["Offset of field: rime_api_t::config_list_size"]
        [::std::mem::offset_of!(rime_api_t, config_list_size) - 544usize];
    ["Offset of field: rime_api_t::config_begin_list"]
        [::std::mem::offset_of!(rime_api_t, config_begin_list) - 552usize];
    ["Offset of field: rime_api_t::get_input"]
        [::std::mem::offset_of!(rime_api_t, get_input) - 560usize];
    ["Offset of field: rime_api_t::get_caret_pos"]
        [::std::mem::offset_of!(rime_api_t, get_caret_pos) - 568usize];
    ["Offset of field: rime_api_t::select_candidate"]
        [::std::mem::offset_of!(rime_api_t, select_candidate) - 576usize];
    ["Offset of field: rime_api_t::get_version"]
        [::std::mem::offset_of!(rime_api_t, get_version) - 584usize];
    ["Offset of field: rime_api_t::set_caret_pos"]
        [::std::mem::offset_of!(rime_api_t, set_caret_pos) - 592usize];
    ["Offset of field: rime_api_t::select_candidate_on_current_page"]
        [::std::mem::offset_of!(rime_api_t, select_candidate_on_current_page) - 600usize];
    ["Offset of field: rime_api_t::candidate_list_begin"]
        [::std::mem::offset_of!(rime_api_t, candidate_list_begin) - 608usize];
    ["Offset of field: rime_api_t::candidate_list_next"]
        [::std::mem::offset_of!(rime_api_t, candidate_list_next) - 616usize];
    ["Offset of field: rime_api_t::candidate_list_end"]
        [::std::mem::offset_of!(rime_api_t, candidate_list_end) - 624usize];
    ["Offset of field: rime_api_t::user_config_open"]
        [::std::mem::offset_of!(rime_api_t, user_config_open) - 632usize];
    ["Offset of field: rime_api_t::candidate_list_from_index"]
        [::std::mem::offset_of!(rime_api_t, candidate_list_from_index) - 640usize];
    ["Offset of field: rime_api_t::get_prebuilt_data_dir"]
        [::std::mem::offset_of!(rime_api_t, get_prebuilt_data_dir) - 648usize];
    ["Offset of field: rime_api_t::get_staging_dir"]
        [::std::mem::offset_of!(rime_api_t, get_staging_dir) - 656usize];
    ["Offset of field: rime_api_t::commit_proto"]
        [::std::mem::offset_of!(rime_api_t, commit_proto) - 664usize];
    ["Offset of field: rime_api_t::context_proto"]
        [::std::mem::offset_of!(rime_api_t, context_proto) - 672usize];
    ["Offset of field: rime_api_t::status_proto"]
        [::std::mem::offset_of!(rime_api_t, status_proto) - 680usize];
    ["Offset of field: rime_api_t::get_state_label"]
        [::std::mem::offset_of!(rime_api_t, get_state_label) - 688usize];
    ["Offset of field: rime_api_t::delete_candidate"]
        [::std::mem::offset_of!(rime_api_t, delete_candidate) - 696usize];
    ["Offset of field: rime_api_t::delete_candidate_on_current_page"]
        [::std::mem::offset_of!(rime_api_t, delete_candidate_on_current_page) - 704usize];
    ["Offset of field: rime_api_t::get_state_label_abbreviated"]
        [::std::mem::offset_of!(rime_api_t, get_state_label_abbreviated) - 712usize];
    ["Offset of field: rime_api_t::set_input"]
        [::std::mem::offset_of!(rime_api_t, set_input) - 720usize];
    ["Offset of field: rime_api_t::get_shared_data_dir_s"]
        [::std::mem::offset_of!(rime_api_t, get_shared_data_dir_s) - 728usize];
    ["Offset of field: rime_api_t::get_user_data_dir_s"]
        [::std::mem::offset_of!(rime_api_t, get_user_data_dir_s) - 736usize];
    ["Offset of field: rime_api_t::get_prebuilt_data_dir_s"]
        [::std::mem::offset_of!(rime_api_t, get_prebuilt_data_dir_s) - 744usize];
    ["Offset of field: rime_api_t::get_staging_dir_s"]
        [::std::mem::offset_of!(rime_api_t, get_staging_dir_s) - 752usize];
    ["Offset of field: rime_api_t::get_sync_dir_s"]
        [::std::mem::offset_of!(rime_api_t, get_sync_dir_s) - 760usize];
    ["Offset of field: rime_api_t::highlight_candidate"]
        [::std::mem::offset_of!(rime_api_t, highlight_candidate) - 768usize];
    ["Offset of field: rime_api_t::highlight_candidate_on_current_page"]
        [::std::mem::offset_of!(rime_api_t, highlight_candidate_on_current_page) - 776usize];
    ["Offset of field: rime_api_t::change_page"]
        [::std::mem::offset_of!(rime_api_t, change_page) - 784usize];
};
pub type RimeApi = rime_api_t;
unsafe extern "C" {
    pub fn rime_get_api() -> *mut RimeApi;
}
