[package]
name = "ime-windows-tsf"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
ime-protocol = { path = "../protocol" }
ime-runtime-core = { path = "../runtime-core" }
ime-pinyin-engine = { path = "../pinyin-engine" }

[target.'cfg(windows)'.dependencies]
ime-broker-transport = { path = "../broker-transport" }
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_Com",
    "Win32_System_LibraryLoader",
    "Win32_System_Registry",
    "Win32_Security",
    "Win32_System_Ole",
    "Win32_System_Variant",
    "Win32_Graphics_Gdi",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_UI_TextServices",
] }
windows-core = "0.62.2"
